/** Phylogeny Editor configuration. Tree is required; TSV and YAML are optional. */
window.PHYLOGENY_VIEWER_CONFIG = {
  title: 'Phylogeny Editor',
  subtitle: 'Author supports, clades, roots, layouts, colors, and tip labels',
  paperTitle: '',
  figureTitle: '',
  authoring: true,
  autoLoad: true,
  treeUrl: './data/nr_to_tree.tree',
  annotationUrl: './data/nr_to_tree.tree_with_last_helix_size.info',
  curationUrl: './data/phylogeny.yaml',
  idColumn: 'id',
  delimiter: '\t',
  defaultColorBy: 'g',
  defaultLayout: 'unrooted',
  defaultUseBranchLengths: true,
  colorColumn: 'color',
  colorTargetColumn: 'g',
  columnLabels: { id: 'Sequence ID', g: 'Group', color: 'Color', last_h50: 'Last H50' },
  tooltipColumns: [],
  filterAliases: { group: 'g', h50: 'last_h50' },
  includePlaceholder: 'Include by ID, group, color, or last_h50…',
  excludePlaceholder: 'Exclude by the same fields…',
  defaultAlignLabels: true,
  defaultBranchScale: 1,
  defaultTipSpacing: 22,
  defaultFitMode: 'all',
  defaultViewZoom: 1,
  defaultTipLabelTemplate: '{tip}',
  defaultSupportDisplay: 'circle',
  defaultSupportColor: '#172033',
  defaultSupportSize: 5,
  defaultSupportNumberSize: 9,
  maxFileBytes: 32 * 1024 * 1024,
  maxTips: 10000,
  showDownloads: true
};
