/** Publication phylogeny configuration. The YAML stores author decisions; source files remain unchanged. */
window.PHYLOGENY_VIEWER_CONFIG = {
  title: 'Phylogeny Viewer',
  subtitle: 'Author-configured clades, supports, labels, and interactive exploration',
  paperTitle: '',
  figureTitle: 'Phylogenetic tree',
  authoring: false,
  autoLoad: true,
  treeUrl: './data/nr_to_tree.tree',
  annotationUrl: './data/nr_to_tree.tree_with_last_helix_size.info',
  curationUrl: './data/phylogeny.yaml',
  idColumn: 'id',
  delimiter: '\t',
  defaultColorBy: 'g',
  defaultLayout: 'unrooted',
  defaultUseBranchLengths: true,
  colorColumn: 'color',
  colorTargetColumn: 'g',
  columnLabels: { id: 'Sequence ID', g: 'Group', color: 'Color', last_h50: 'Last H50' },
  tooltipColumns: ['id', 'g', 'last_h50'],
  filterAliases: { group: 'g', h50: 'last_h50' },
  includePlaceholder: 'Include by any tip or annotation field…',
  excludePlaceholder: 'Exclude by the same fields…',
  defaultAlignLabels: true,
  defaultBranchScale: 1,
  defaultTipSpacing: 22,
  defaultFitMode: 'all',
  defaultViewZoom: 1,
  defaultTipLabelTemplate: '{tip}',
  defaultSupportDisplay: 'circle',
  defaultSupportColor: '#172033',
  defaultSupportSize: 5,
  defaultSupportNumberSize: 9,
  maxFileBytes: 32 * 1024 * 1024,
  maxTips: 10000,
  showDownloads: true
};
